pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g ottomatica/opunit#dev
  displayName: 'Install opunit'
  
- script: |
    sudo apt-get install python python-pip
    sudo pip install ansible
  displayName: 'Install Ansible'

- script: |
    cd lang/nodejs
    ansible-playbook --connection=local --inventory localhost, nodejs9.yml
  displayName: 'Run node9.yml'

- script: |
    node --version 
  displayName: 'Check java version'
  
# - script: | 
#     ssh-keygen -t rsa -N "" -f localhost.key
#     mkdir -p ~/.ssh
#     cat localhost.key.pub >> ~/.ssh/authorized_keys
#     chmod og-wx ~/.ssh/authorized_keys 

- script: | 
    ls -al
    echo "$USER"
    cd lang/nodejs
    opunit verify local -c ./opunit.yml
  displayName: 'Opunit verify'
