pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g ottomatica/opunit#dev
  displayName: 'Install opunit'
  
- script: |
    sudo apt-get install python python-pip
    sudo pip install ansible
  displayName: 'Install Ansible'

- script: |
    cd lang/java
    ansible-playbook --connection=local --inventory localhost, java8.yml
  displayName: 'Run java8.yml'

- script: |
    java -version 
  displayName: 'Check java version'
  
- script: | 
    ssh-keygen -t rsa -N "" -f localhost.key
    mkdir -p ~/.ssh
    cat localhost.key.pub >> ~/.ssh/authorized_keys
    chmod og-wx ~/.ssh/authorized_keys 

- script: | 
    ls -al
    echo "$USER"
    cd lang/java
    opunit verify "$USERR@localhost:22" -c ./opunit.yml --ssh_key ../../localhost.key 
  displayName: 'Opunit verify'
